SELECT 0 as ROWNUM,
       count(DISTINCT DIST_ACCT) AS TOTAL_STOPS,
       count(DISTINCT DIST_ACCT) - count(DISTINCT TRK.SGTACCTID) AS REMAINING_STOPS,
       count(DISTINCT TRK.SGTACCTID) AS COMPLETE_STOPS,
       sum(case when ROWNR2 = 1 then QTY else 0 end) AS CASES_NUMBER,
       sum(case when ROWNR = 1 and SGTVALUE2 is not null and SGTVALUE2 <> '' then SGTVALUE2 else 0 end) AS CASES_ORDERED,
       sum(case when ROWNR = 1 and SGTVALUE1 is not null and SGTVALUE1 <> '' then SGTVALUE1 else 0 end) AS CASES_DELIVERED,
       sum(case when ROWNR = 1 and SGTVALUE2 is not null and SGTVALUE2 <> '' then SGTVALUE2 else 0 end) + 0 - sum(case when ROWNR = 1 and SGTVALUE1 is not null and SGTVALUE1 <> '' then SGTVALUE1 else 0 end) AS CASES_RETURNED,
       sum(case when ROWNR2 = 1 then QTY else 0 end) - sum(case when ROWNR = 1 and SGTVALUE1 is not null and SGTVALUE1 <> '' then SGTVALUE1 else 0 end) AS CASES_REMAINING,
       TRK.DIST AS TRK_DIST,
       TRK.DDBA AS TRK_DDBA,
       TRK.LOAD AS TRK_LOAD
from ( select SVA.SVAVPID, SVA.SVAACCTID, SVA.SVAACCT ACCOUNT_CODE, SVAROUTENM SALESMAN_NAME, SVAROUTENO SALESMAN_NBR, SVA.SVAACCT, SVA.SVADBA,
              SVA.SVAADDR, SVA.SVACITY, SVA.SVASTATE, SVA.SVAZIP5, SVA.SVALONG, SVA.SVALAT, SVA.SVAPREMISE, SVA.SVACOTID, SVA.SVACOTDSC,
              SVA.SVASCOTID, SVA.SVASCOTDSC, SVA.SVAVPCHNID, SVA.SVAVPCHNM, SVA.SVACHNSTS, SVA.SVAWHSEID, SVA.SVAWHSEDSC, SVA.SVACOMPID,
              SVA.SVACOMPDSC, SVA.SVASUPRID, SVA.SVASUPRDSC, SVA.SVAACTPTYP, SVA.SVASVCDIST, SGT.SGTACCTID, SGT.SGTVALUE1, SGT.SGTVALUE2,
              SGT.SGTVALUE3, SGT.SGTVALUE4, SGT.SGTVALUE5, DD.DIST, DD.DDBA, SO.DIST_ACCT, SO.QTY, SO.DATE, SO.LOAD, RTE.RTSEQ,
              ROW_NUMBER() over (PARTITION BY SO.LOAD, SO.SVAACCTID, SO.DATE, SGTTRKTIM) as ROWNR,
              ROW_NUMBER() over (PARTITION BY SO.DAIDENTITY) as ROWNR2
       from SR_XXX.FCTSALES_ORDERS SO
           join SR_XXX.DIMDIST DD on (SO.DIST = DD.DIST)
           left join SR_XXX.SVYDSRMAS RTE on (RTE.DRVID = SO.DRVID and RTE.SVAACCT = SO.DIST_ACCT and RTE.TDATE = SO.TDATE)
           left join SR_XXX.SVGPSTRKT SGT on (SO.SVAACCTID = SGT.SGTACCTID and SGT.SGTVALUE5 = SO.LOAD and SGT.SGTEVENT = 'delinvoice' and SO.DATE = to_char(SGT.SGTTRKTIM, 'YYYYMMDD'))
           left join SR_XXX.SVACCTT SVA on (SO.SVAACCTID = SVA.SVAACCTID) ) TRK
where 1=1  and DATE >= ? and DATE <= ?  group by TRK.DIST, TRK.DDBA, TRK.LOAD ORDER BY TRK.DDBA ASC, TRK.LOAD ASC FOR FETCH ONLY


SELECT 0 as ROWNUM, SVQ.SVQQSTID AS SVQ_SVQQSTID, SVQ.SVQQSTTXT AS SVQ_SVQQSTTXT, SVQ.SVQCATID AS SVQ_SVQCATID, QCAT.QCATDESC AS QCAT_QCATDESC,
       SVQ.SVQQSTTYP AS SVQ_SVQQSTTYP, SVQ.SVQSTATUS AS SVQ_SVQSTATUS, SVQ.SVQLOOPTP AS SVQ_SVQLOOPTP,
       (case when SVQLOOPTP = 'NOLOOP' then 0 when SVQLOOPTP = 'LOC' then 1 when SVQLOOPTP = 'LOCBRAND' then 2 when SVQLOOPTP = 'LOCITEM' then 3 when SVQLOOPTP = 'BRAND' then 4 when SVQLOOPTP = 'ITEM' then 5 else 0 end) AS QUESTION_LOOP_ORDER,
       SVQ.SVQCUSTID AS SVQ_SVQCUSTID, SVQ.SVQDFTANW AS SVQ_SVQDFTANW, SVQ.SVQANWTYP AS SVQ_SVQANWTYP, ANT.ANTDESC AS ANT_ANTDESC, ANT.ANTLOOKUP AS ANT_ANTLOOKUP,
       ANT.ANTFLDTYP AS ANT_ANTFLDTYP, ANT.ANTTABLE AS ANT_ANTTABLE, ANT.ANTFIELD AS ANT_ANTFIELD, SVQ.SVQALWFRE AS SVQ_SVQALWFRE,
       (case when count(SVHSTATUS) > 0 then 'Y' else 'N' end) AS QUESTION_USED, max(SAHENDDAT) AS QUESTION_LAST_USED,
       SVQ.SVQCRTTIM AS SVQ_SVQCRTTIM, to_char(SVQCRTTIM,'YYYYMMDD') AS CREATE_DATE, SVQ.SVQCRTUSR AS SVQ_SVQCRTUSR, EMC.NAME AS EMC_NAME,
       SVQ.SVQUPDTIM AS SVQ_SVQUPDTIM, to_char(SVQUPDTIM,'YYYYMMDD') AS UPDATE_DATE, SVQ.SVQUPDUSR AS SVQ_SVQUPDUSR, EMU.NAME AS EMU_NAME
from  FR_SRS.SVYQS2XRFT SQX  join  FR_SRS.SVYQSTDTAT as SVQ on (SQX.SQXQSTID = SVQ.SVQQSTID  and SQXCUSTID = 'XXX')
    join  FR_SRS.SVYANWXRFT SAX  on (SAX.SAXANWID = SVQ.SVQANWTYP and SAX.SAXCUSTID = 'XXX')
    join  FR_SRS.SVYANWTYPT as ANT on (SAX.SAXANWID = ANT.ANTATYPID )
    left join FR_SRS.SVYTMLDTLT SVD on (SVD.SVDQSTID = SVQ.SVQQSTID)
    left join FR_SRS.SVYTMLXRFT STX  on (STX.STXSVYID = SVD.SVDSVYID and STX.STXCUSTID = 'XXX')
    left join FR_SRS.SVYTMLHDRT as SVH on (STX.STXSVYID = SVH.SVHSVYID )
    left join SR_XXX.SVYASGHDRT SAH ON (SAH.SAHSVYID = SVH.SVHSVYID)
    left join FR_SRS.SVYQSTCATT QCAT on (SVQ.SVQCATID = QCAT.QCATID and QCAT.QCATSTS <> 'D')
    left join FR_SRS.EMPMASTT EMC on (SVQ.SVQCRTUSR = EMC.EMUID)
    left join FR_SRS.EMPMASTT EMU on (SVQ.SVQUPDUSR = EMU.EMUID)
WHERE ( SVQ.SVQQSTID = ? ) group by SVQ.SVQQSTID, SVQ.SVQQSTTXT, SVQ.SVQCATID, QCAT.QCATDESC, SVQ.SVQQSTTYP, SVQ.SVQSTATUS, SVQ.SVQLOOPTP, SVQ.SVQCUSTID, SVQ.SVQDFTANW, SVQ.SVQANWTYP, ANT.ANTDESC, ANT.ANTLOOKUP, ANT.ANTFLDTYP, ANT.ANTTABLE, ANT.ANTFIELD, SVQ.SVQALWFRE, SVQ.SVQCRTTIM, SVQ.SVQCRTUSR, EMC.NAME, SVQ.SVQUPDTIM, SVQ.SVQUPDUSR, EMU.NAME    FOR FETCH ONLY